# Generated by Django 4.0.3 on 2022-03-08 08:10

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                # ('program', models.ForeignKey(to='Program')),
                ('program', models.UUIDField()),
                # ('bank', models.ForeignKey(to='Bank')),
                ('bank', models.UUIDField()),
                ('country', models.TextField(unique=True)),
                ('is_eligible', models.BooleanField(default=True)),
            ],
        ),
    ]

